language: rust
cache: cargo
matrix:
  include:
    - rust: stable
      script:
        - |
          cargo test --all-features &&
          cargo fmt -- --check &&
          cargo clippy --all-features -- -D clippy::all
