[package]
name = "buttons"
version = "0.4.0"
authors = ["Vi <violet@hey.com>"]
description = "A simple API for storing and querying input state."
edition = "2021"
homepage = "https://github.com/mistodon/buttons"
repository = "https://github.com/mistodon/buttons"
readme = "README.md"
keywords = ["input", "keyboard", "mouse", "touch"]
categories = ["games"]
license = "CC0-1.0"

[package.metadata.docs.rs]
all-features = true

[dependencies.winit]
version = "~0.26.0"
optional = true

[dev-dependencies.winit]
version = "~0.26.0"

[features]
default = []
winit = ["dep:winit"]
