[package]
name = "buttons"
version = "0.1.0"
authors = ["Claire Harris <wishing.engine@gmail.com>"]

[features]
default = []
winit_support = ["winit"]

[dependencies.winit]
version = "~0"
optional = true
