[package]
name = "buttons"
version = "0.1.0"
authors = ["***Realname*** ***Lastname*** <***redacted.email@redacted.nope***>"]

[features]
default = []
winit_support = ["winit"]

[dependencies.winit]
version = "~0"
optional = true
