[package]
name = "buttons"
version = "0.1.0"
authors = ["***Realname*** ***Lastname*** <***redacted.email@redacted.nope***>"]

[dependencies.winit]
version = ">= 0.6.0"
optional = true

[features]
winit-support = ["winit"]
