#!/bin/bash

set -e

echo -e "\033[36;1mRunning tests:\033[0m"
cargo test --all-features

echo -e "\033[36;1mRunning rustfmt:\033[0m"
cargo fmt -- --check

echo -e "\033[36;1mRunning clippy:\033[0m"
cargo clippy --all-features -- -D clippy::all
